Update main.yml
Adding a step to check the presence of .scannerwork directory

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,6 +38,15 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
+      - name: Check if .scannerwork directory exists
+        run: |
+          if [ -d "${{ github.workspace }}/.scannerwork" ]; then
+          echo ".scannerwork directory exists"
+          else
+          echo "ERROR: .scannerwork directory does not exist"
+          exit 1
+          fi
         
       - name: SonarQube Quality Gate Check
         uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
